### ISSUE TITLE
Clarify whether virtual (combo) fonts can be used to fake small caps

### ISSUE THREAD

**Issue by callegar** [u-fischer/combofont#1]
If I understand properly, in regular latex the virtual fonts mechanism is used to provide the small caps feature to fonts that miss it, such as the ptm (times) font.

I wonder if the current features of luaotfload and combofont can be used to get a similar result with lualatex and (if the answer is positive) how.

**Comment by u-fischer** [comment]
I don't think that it would make much sense to use combofont for this. combofont is about combining two fonts not about moving glyphs of one font around (and scaling them). One could probably do it with a virtual font, but I doubt that it is worth the trouble: fake small caps seldom look very satifactory.

**Comment by callegar** [comment]
Wonder if you may know some pointer ad docs on at how to set up virtual fonts in lualatex (or xelatex) with modern fonts in order to actually move glyphs around and apply transformations such as scaling to them. I would like to move production of some documents from pdflatex to lualatex to take advantage of the new features and the true unicode support, but one of my issues is maintaining visual consistency with the series with so far uses "ptm", i.e. Nimbus Roman. With "ptm" small caps is emulated (and not too bad to look at). The main obstacle is that using Nimbus Roman in its OTF fontspec loaded incarnation provides no small caps at all. Trying to use other Times-like fonts is impossible, because small caps is rather different in TeX Gyre Termes (much smaller) while STIX Two text provides a similarly looking small caps, but has metrics incompatible with those of Nimbus Roman or Times New Roman. In other words, all the alternatives that I have investigated (am I missing some?) look even less satisfactory than fake small caps.

**Comment by callegar** [comment]
Digging in the matter a bit further, it looks like the TeX Gyre Small Caps should actually be Petite Caps (small caps as tall as the x height) and that they are also obtained programmatically from regular uppercase. In this sense, they are also fake small caps, as it seems to be the case for many free fonts. In other words, there is no reason why faking small caps programmatically a the LaTeX level should be much less satisfactory than doing it in a similar programmatic way during the OTF font assembly. Conversely, it would provide more flexibility (e.g., in setting the scale, etc.).

**Comment by u-fischer** [comment]
The issue tracker of this package is the wrong place to ask this. Ask at tex.stackexchange or on the luatex mailing list.
